config/urls.py
from allauth.account.views import LoginView
from axes.decorators import axes_dispatch, axes_form_invalid
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.decorators import method_decorator
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from django_portal_template.apps.users.forms import AxesLoginForm

LoginView.dispatch = method_decorator(axes_dispatch)(LoginView.dispatch)
LoginView.form_invalid = method_decorator(axes_form_invalid)(LoginView.form_invalid)


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("django_portal_template.apps.users.urls", namespace="users")),
    # Override allauth default login view with a patched view
    path(
        "accounts/login/",
        LoginView.as_view(form_class=AxesLoginForm),
        name="account_login",
    ),
    path("accounts/", include("allauth_2fa.urls")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    # Core app content.
    path("", include("django_portal_template.apps.core.urls", namespace="core")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

django_portal_template/apps/core/urls.py
# from django.urls import path

app_name = "core"
urlpatterns = []

django_portal_template/apps/users/urls.py
from django.urls import path

from django_portal_template.apps.users.views import user_detail_view, user_redirect_view, user_settings_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
    path("settings/", view=user_settings_view, name="user_settings_view"),
]

django_portal_template/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from django_portal_template.apps.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Django Portal Template.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

django_portal_template/apps/users/forms.py
from allauth.account.forms import LoginForm, SignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class AxesLoginForm(LoginForm):
    """
    Extended login form class that supplied the
    user credentials for Axes compatibility.
    """

    def user_credentials(self):
        credentials = super().user_credentials()
        credentials["login"] = credentials.get("email") or credentials.get("username")
        return credentials

django_portal_template/apps/core/views.py
# Create your views here.

django_portal_template/apps/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "pk"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

django_portal_template/apps/users/views.py
from axes.models import AccessLog
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.gis.geoip2 import GeoIP2
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DetailView, RedirectView
from django_otp.plugins.otp_static.models import StaticDevice
from django_otp.plugins.otp_totp.models import TOTPDevice

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()


@login_required
def user_settings_view(request):
    """
    User settings page. Collates all user and account view links into a single user page.
    Also displays an access log.
    """
    user = request.user
    totp_dev = TOTPDevice.objects.devices_for_user(user, confirmed=True)
    static_dev = StaticDevice.objects.devices_for_user(user, confirmed=True)

    g = GeoIP2()
    access_history = []
    for log in AccessLog.objects.filter(username=user).order_by("-attempt_time")[:30]:
        try:
            geo_ip = g.city(log.ip_address)
            access_history.append(
                {
                    "device": log.user_agent,
                    "location": str(geo_ip["city"]) + ", " + str(geo_ip["country_name"]),
                    "ip_address": log.ip_address,
                    "time": log.attempt_time,
                }
            )
        except Exception:
            access_history.append(
                {
                    "device": log.user_agent,
                    "location": "Unknown",
                    "ip_address": log.ip_address,
                    "time": log.attempt_time,
                }
            )

    return render(
        request,
        "users/user_settings_page.html",
        {
            "totp_dev": totp_dev,
            "static_dev": static_dev,
            "access_history": access_history,
        },
    )

django_portal_template/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}
  Forbidden (403)
{% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

django_portal_template/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
{% load django_bootstrap5 %}

{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Django Portal Template
      {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
          content="A user portal template built using Django Cookiecutter, AWS and OTP security." />
    <meta name="author" content="i-am-LC" />
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
    {% block css %}
      <!-- Latest compiled and minified Bootstrap CSS -->
      <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
            integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer" />
      <link rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" />
      <!-- Your stuff: Third-party CSS libraries go here -->
      <!-- https://demo.adminkit.io/index.html -->
      <link rel="stylesheet"
            href="https://unpkg.com/@adminkit/core@latest/dist/css/app.css" />
      <!-- This file stores project-specific CSS -->
      <link href="{% static 'css/project.css' %}" rel="stylesheet" />
    {% endblock css %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}
      <!-- Bootstrap JS -->
      <script defer
              src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
              integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- https://demo.adminkit.io/index.html -->
      <script src="https://unpkg.com/@adminkit/core@latest/dist/js/app.js"></script>
      <!-- place project specific Javascript in this file -->
      <script defer src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body>
    <div class="main">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="{% static '' %}" alt="LOGO" width="120" height="37" />
          </img />
        </a>
        {% if request.user.is_authenticated %}
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent"
                  aria-controls="navbarSupportedContent"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link text-white"
                   href="{% url 'users:detail' request.user.pk %}">{% translate "Profile" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white"
                   href="{% url 'users:user_settings_view' %}">{% translate "Settings" %}</a>
              </li>
              <li class="nav-item">
                {% if user.is_staff %}
                  <a class="nav-link text-white" href="{% url 'admin:index' %}">{% translate "Admin" %}</a>
                {% endif %}
              </li>
            </ul>
            <div class="d-flex">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                  {# URL provided by django-allauth/account/urls.py #}
                  <a href="{% url 'account_logout' %}"
                     type="button"
                     class="btn btn-outline-light me-2">{% translate "Logout" %}</a>
                </li>
              </ul>
            </div>
          </div>
        {% else %}
          <div class="justify-content-end">
            {# URL provided by django-allauth/account/urls.py #}
            <a href="{% url 'account_login' %}"
               type="button"
               class="btn btn-outline-light me-1">{% translate "Login" %}</a>
            {% if ACCOUNT_ALLOW_REGISTRATION %}
              <a href="{% url 'account_signup' %}"
                 type="button"
                 class="btn btn-warning text-black ">{% translate "Sign Up" %}</a>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </nav>
    <!-- Content & Alerts -->
    <main class="content">
      <div class="container-fluid p-0">
        <!-- Alerts -->
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible text-center {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="alert"
                      aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        <!-- Content -->
        <div class="row">
          <div class="col-12">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      </div>
    </main>
    {% block modal %}
    {% endblock modal %}
    {% block inline_javascript %}
      {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
      {% endcomment %}
    {% endblock inline_javascript %}
    <!-- Footer -->
    <footer class="footer">
      <div class="container-fluid">
        <div class="row text-muted">
          <div class="col-3 text-start">
            <p class="mb-0">
              <a href="" target="_blank" class="text-muted">
                <img src="{% static '' %}"
                     alt="LOGO"
                     width="150"
                     height="25"
                     class="d-inline-block align-text-top" />
              </a>
            </p>
          </div>
          <div class="col-9 text-end">
            <ul class="list-inline pt-2">
              <li class="list-inline-item">
                <a href="mailto: info@example.com" class="text-muted">
                  <i class="bi bi-envelope-at"></i>
                  info@example.com
                </a>
              </li>
              <li class="list-inline-item">
                <a href="tel:1300123456" class="text-muted">
                  <i class="bi bi-telephone"></i>
                  1300 123 456
                </a>
              </li>
              <li class="list-inline-item">
                <i class="bi bi-building"></i>
                123 Alphabet Street, Melbourne, VIC 3000
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>